# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master
- refs/tags/*

pr:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'SchildExport.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  displayName: 'nuget restore'
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: 'Build Solution'
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: NuGetCommand@2
  displayName: 'nuget pack'
  inputs:
    command: pack
    packagesToPack: '**\*.nuspec'

- task: GitHubRelease@0
  displayName: Release nightly to GitHub
  inputs:
    gitHubConnection: 'GitHub.com'
    repositoryName: schulit/schildexport
    tagSource: manual
    tag: nightly
    assets: '**\*.dll'
    assetUploadMode: replace
  condition: succeeeded()

- task: NuGetCommand@2
  displayName: 'nuget push'
  inputs:
    command: push
    publishFeedCredentials: 'NuGet.org'
    nuGetFeedType: external
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))

- task: GitHubRelease@0
  displayName: Release to GitHub
  inputs:
    gitHubConnection: 'GitHub.com'
    repositoryName: schulit/schildexport
    assets: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
